# -*- conf -*-

#shell=/run/current-system/sw/bin/zsh

[main]
#font=FiraCode Nerd Font Mono:size=10,Noto Color Emoji:size=10

#font=Iosevka:style=Bold:size=10
#font=FiraCode Nerd Font Mono:size=12   
#font-bold=Iosevka:style=Bold:size=10
#font-italic=Iosevka:style=Italic:size=10
#font-bold-italic=Iosevka:style=Bold Italic:size=10

font=FiraCode Nerd Font Mono:size=12   
font-bold=FiraCode Nerd Font Mono:size=12
font-italic=FiraCode Nerd Font Mono:size=12
font-bold-italic=FiraCode Nerd Font Mono:size=12




# testing new stuff
# -----------
underline-offset=4px
strikeout-thickness=1px
pad=10x5
line-height=20px
# ----------

[scrollback]
lines=10000

[key-bindings]
clipboard-copy=Control+c XF86Copy
clipboard-paste=Control+v XF86Paste

#scrollback-up-page=Shift+Up
#scrollback-down-page=Shift+Down
#scrollback-up-line=Control+Shift+Up
#scrollback-down-line=Control+Shift+Down

[search-bindings]
cancel=Control+g Control+Shift+c Escape

[url-bindings]
cancel=Control+g Control+Shift+c Control+d Escape

[cursor]
style=block
unfocused-style=hollow


[mouse]
hide-when-typing=true

[colors-dark]
cursor=fb008f 3d85c6 

background=0a0a20
foreground=ffffff

regular0=d32f2f
regular1=ff4081
regular2=4caf50
regular3=ffeb3b
regular4=2196f3
regular5=9c27b0
regular6=00bcd4
regular7=607d8b

bright0=ff5722
bright1=ff9800
bright2=00e676
bright3=cddc39
bright4=009688
bright5=673ab7
bright6=3f51b5
bright7=ffffff


# old color scheme ------
#[colors]
#cursor=ffffff 0a0a20
#
#background=0a0a20
#foreground=ffffff
#
#regular0=d32f2f
#regular1=ff4081
#regular2=4caf50
#regular3=ffeb3b
#regular4=2196f3
#regular5=9c27b0
#regular6=00bcd4
#regular7=607d8b
#
#bright0=ff5722
#bright1=ff9800
#bright2=00e676
#bright3=cddc39
#bright4=009688
#bright5=673ab7
#bright6=3f51b5
#bright7=ffffff
# ----------------------


#selection-foreground=000000
#selection-background=80deea

[tweak]
font-monospace-warn=no
