
# Run rainbow borders animation
exec= bash -x $configs/scripts/smooth_RainbowBorder.sh

# Good tips from Vimjoyer or LibrePhoenix!
# Create shell command to run hyprland.conf
exec-once=bash ~/.config/hypr/start_hyprland.sh
