# See https://wiki.hyprland.org/Configuring/Monitors/
#monitor=,preferred,auto,auto

# Main screen
monitor = eDP-1, 2560x1600@165, 0x0, 1

# Lenovo portable screen
monitor = DP-2, preferred, auto, 1
monitor = DP-4, preferred, auto, 1

# ASUS ultrawide at home
#monitor = HDMI-A-1, preferred, auto, 1
monitor = HDMI-A-1, preferred, auto, 1, mirror, eDP-1



# Assign workspaces
workspace = 1, monitor:eDP-1



# Mirrored monitors (never forget Fontys 2026 prp presentation :holding_back_tears:)
# https://wiki.hypr.land/0.41.2/Configuring/Monitors/
