#! /bin/bash

#preload = /home/nansus/.dotfiles/system/wallpaper/what_are_you_talking_to_me.png

#wallpaper = ,/home/nansus/.dotfiles/system/wallpaper/what_are_you_talking_to_me.png

#splash = false


#preload = /home/nansus/.dotfiles/system/wallpaper/Under_Starlit_Sky.png

#wallpaper = ,/home/nansus/.dotfiles/system/wallpaper/Under_Starlit_Sky.png

#splash = false




wallpaper {
    monitor = 
    path = /home/nansus/.dotfiles/system/wallpaper/Under_Starlit_Sky.png
    fit_mode = cover
}
